
version: '3.7'

services:

  nginx:
    build:
      context: src/nginx_stub
    container_name: test-nginx
    depends_on:
      - languages-chooser-server
    image: cyberdojo/nginx_languages_stub
    init: true
    ports: [ "80:80" ]
    user: root

  #- - - - - - - - - - - - - - - - - - - - - - - - - - -
  languages-chooser-client:
    build:
      args: [ COMMIT_SHA, CYBER_DOJO_LANGUAGES_CHOOSER_CLIENT_PORT ]
      context: src/client
    container_name: test-languages-chooser-client
    depends_on:
      - languages-chooser-server
      - selenium
    image: cyberdojo/test-languages-chooser-client
    init: true
    ports: [ "${CYBER_DOJO_LANGUAGES_CHOOSER_CLIENT_PORT}:${CYBER_DOJO_LANGUAGES_CHOOSER_CLIENT_PORT}" ]
    read_only: true
    restart: "no"
    tmpfs: /tmp
    user: nobody
    volumes: [ "./test:/test/:ro" ]

  #- - - - - - - - - - - - - - - - - - - - - - - - - - -
  languages-chooser-server:
    build:
      args: [ COMMIT_SHA, CYBER_DOJO_LANGUAGES_CHOOSER_PORT ]
      context: src/server
    container_name: test-languages-chooser-server
    depends_on:
      - languages-start-points
      - creator
    environment: [ NO_PROMETHEUS ]
    image: ${CYBER_DOJO_LANGUAGES_CHOOSER_IMAGE}
    init: true
    ports: [ "${CYBER_DOJO_LANGUAGES_CHOOSER_PORT}:${CYBER_DOJO_LANGUAGES_CHOOSER_PORT}" ]
    read_only: true
    restart: "no"
    tmpfs: /tmp
    user: nobody
    volumes: [ "./test:/test/:ro" ]

  #- - - - - - - - - - - - - - - - - - - - - - - - - - -
  languages-start-points:
    environment: [ NO_PROMETHEUS ]
    image: ${CYBER_DOJO_LANGUAGES_START_POINTS_IMAGE}:${CYBER_DOJO_LANGUAGES_START_POINTS_TAG}
    init: true
    ports: [ "${CYBER_DOJO_LANGUAGES_START_POINTS_PORT}:${CYBER_DOJO_LANGUAGES_START_POINTS_PORT}" ]
    read_only: true
    restart: 'no'
    tmpfs: /tmp
    user: nobody

  #- - - - - - - - - - - - - - - - - - - - - - - - - - -
  creator:
    depends_on:
      - custom-start-points
      - exercises-start-points
      - languages-start-points
      - saver
    environment: [ NO_PROMETHEUS ]
    image: ${CYBER_DOJO_CREATOR_IMAGE}:latest
    init: true
    ports: [ "${CYBER_DOJO_CREATOR_PORT}:${CYBER_DOJO_CREATOR_PORT}" ]
    read_only: true
    restart: 'no'
    tmpfs: /tmp
    user: nobody

  #- - - - - - - - - - - - - - - - - - - - - - - - - - -
  custom-start-points:
    environment: [ NO_PROMETHEUS ]
    image: ${CYBER_DOJO_CUSTOM_START_POINTS_IMAGE}:${CYBER_DOJO_CUSTOM_START_POINTS_TAG}
    init: true
    ports: [ "${CYBER_DOJO_CUSTOM_START_POINTS_PORT}:${CYBER_DOJO_CUSTOM_START_POINTS_PORT}" ]
    read_only: true
    restart: 'no'
    tmpfs: /tmp
    user: nobody

  #- - - - - - - - - - - - - - - - - - - - - - - - - - -
  exercises-start-points:
    environment: [ NO_PROMETHEUS ]
    image: ${CYBER_DOJO_EXERCISES_START_POINTS_IMAGE}:${CYBER_DOJO_EXERCISES_START_POINTS_TAG}
    init: true
    ports: [ "${CYBER_DOJO_EXERCISES_START_POINTS_PORT}:${CYBER_DOJO_EXERCISES_START_POINTS_PORT}" ]
    read_only: true
    restart: 'no'
    tmpfs: /tmp
    user: nobody

  #- - - - - - - - - - - - - - - - - - - - - - - - - - -
  saver:
    environment: [ NO_PROMETHEUS ]
    image: ${CYBER_DOJO_SAVER_IMAGE}:${CYBER_DOJO_SAVER_TAG}
    init: true
    ports: [ "${CYBER_DOJO_SAVER_PORT}:${CYBER_DOJO_SAVER_PORT}" ]
    read_only: true
    restart: 'no'
    tmpfs:
      - /cyber-dojo:uid=19663,gid=65533
      - /tmp:uid=19663,gid=65533
    user: saver

  #- - - - - - - - - - - - - - - - - - - - - - - - - - -
  selenium:
    image: selenium/standalone-firefox
    ports: [ "4444:4444" ]
