
fullnameOverride: "languages"

replicaCount: 3

service:
  port: 4524
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "4524"

volumes:
  - name: languages-tmp-dir
    emptyDir:
      medium: Memory
      sizeLimit: "16Mi"

containers:
  - name: languages
    env:
      PROMETHEUS_COLLECTOR_METRICS_PREFIX: "languages"  
    image: cyberdojo/languages-all
    securityContext:
      readOnlyRootFilesystem: true
    volumeMounts:
      - name: languages-tmp-dir
        mountPath: /tmp
        readOnly: false
    resources:
      limits:
        memory: 32Mi
      requests:
        memory: 32Mi
    livenessProbe:
      path: /alive?
      port: 4524
    readinessProbe:
      path: /ready?
      port: 4524

envFromSecret: {}

nodeSelector: {}

affinity: {}

tolerations: []
